id: I24D614A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T13:10:35+00:00'
last_modified: '2022-06-07T15:22:22.089093+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23453
  title: ཐུགས་སྒྲུབ་དྲག་པོ་རྩལ་གྱི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AD0D:
      image_group_id: I4177
      title: ''
      total_pages: 600
      order: 1
      base_file: AD0D.txt
    10A4:
      image_group_id: I4178
      title: ''
      total_pages: 580
      order: 2
      base_file: 10A4.txt
    C3D9:
      image_group_id: I4179
      title: ''
      total_pages: 524
      order: 3
      base_file: C3D9.txt
    D4AC:
      image_group_id: I4180
      title: ''
      total_pages: 566
      order: 4
      base_file: D4AC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
