id: I24D614A3
legacy_id: P001848
ocr_import_info:
  bdrc_scan_id: W23453
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T13:06:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:07:36.969544+00:00'
last_modified: 2022-09-02 09:08:21.596684
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23453
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23453
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུགས་སྒྲུབ་དྲག་པོ་རྩལ་གྱི་ཆོས་སྐོར།
  author: རིག་འཛིན་རྒོད་ཀྱི་ལྡེམ་འཕྲུ་ཅན།
statistics:
  ocr_word_mean_confidence_index: 0.6728212702143618
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I4178:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4178
      total_pages: 580
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4178.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6446227389673199
    legacy_id: v002
  I4177:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4177
      total_pages: 600
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4177.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.679705154250467
    legacy_id: v001
  I4179:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4179
      total_pages: 524
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4179.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.658999537882118
    legacy_id: v003
  I4180:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4180
      total_pages: 566
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4180.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6980758116453981
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
