id: P001848
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23453
  title: ཐུགས་སྒྲུབ་དྲག་པོ་རྩལ་གྱི་ཆོས་སྐོར
  author: ''
  volumes:
    c9c2d3a6af684a7196086bc66b720d49:
      image_group_id: I4177
      title: ''
      volume_number: 1
      total_pages: 600
      base_file: v001.txt
    66f30de1291c42bda8a76fd9aabbd921:
      image_group_id: I4178
      title: ''
      volume_number: 2
      total_pages: 580
      base_file: v002.txt
    1c5db6dd174e47c8a8f8bd6a52745696:
      image_group_id: I4179
      title: ''
      volume_number: 3
      total_pages: 524
      base_file: v003.txt
    b7d7cab04ec34b95856b04081ec916f6:
      image_group_id: I4180
      title: ''
      volume_number: 4
      total_pages: 566
      base_file: v004.txt
